version: "3.1"

services:

  db:
    image: postgres:14.2-alpine
    restart: always
    container_name: postgresql
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: g1lv@n
      POSTGRES_USER: gilvan
      POSTGRES_DB: agendamento
      
    ports:
      - "5432:5432"